name: Distance_copying_TFM
channels:
  - conda-forge
  - defaults
dependencies:
  - absl-py=2.1.0=py312haa95532_0
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.0=pyh2a7be5b_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - ansicolors=1.1.8=pyhd8ed1ab_0
  - anyio=4.10.0=py312haa95532_0
  - aom=3.6.0=hd77b12b_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=25.1.0=py312h02ab6af_0
  - asttokens=3.0.0=py312haa95532_0
  - astunparse=1.6.3=py_0
  - async-lru=2.0.4=py312haa95532_0
  - async-timeout=5.0.1=pyhd8ed1ab_1
  - attrs=24.3.0=py312haa95532_0
  - babel=2.16.0=py312haa95532_0
  - beautifulsoup4=4.13.5=py312haa95532_0
  - blas=1.0=mkl
  - bleach=6.2.0=py312haa95532_0
  - bottleneck=1.4.2=py312h4b0e54e_0
  - brotli-python=1.0.9=py312h5da7b33_9
  - brotlicffi=1.0.9.2=py312h5da7b33_1
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.34.5=h731ff69_0
  - ca-certificates=2025.10.5=h4c7d964_0
  - cairo=1.18.4=he9e932c_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=1.17.1=py312h827c3e9_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.3.0=pyh7428d3b_0
  - colorama=0.4.6=py312haa95532_0
  - comm=0.2.1=py312haa95532_0
  - contourpy=1.3.1=py312h214f63a_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dav1d=1.2.1=h2bbff1b_0
  - debugpy=1.8.16=py312h885b0b7_0
  - decorator=5.2.1=py312haa95532_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=pyhd8ed1ab_1
  - executing=2.2.1=py312haa95532_0
  - expat=2.7.1=h8ddb27b_0
  - fontconfig=2.14.1=hb33846d_3
  - fonttools=4.59.2=py312h02ab6af_0
  - freeglut=3.4.0=h8a1e904_1
  - freetype=2.13.3=h0620614_0
  - fribidi=1.0.10=h62dcd97_0
  - frozenlist=1.7.0=pyhf298e5d_0
  - gast=0.6.0=pyhd3eb1b0_0
  - giflib=5.2.2=h7edc060_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - graphite2=1.3.14=hd77b12b_1
  - grpcio=1.71.0=py312hbb1fe6b_0
  - h11=0.16.0=py312haa95532_0
  - h5py=3.14.0=py312h6fc9867_0
  - harfbuzz=10.2.0=he2f9f60_1
  - hdf5=1.14.5=ha36df97_2
  - httpcore=1.0.9=py312haa95532_0
  - httpx=0.28.1=py312haa95532_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - idna=3.7=py312haa95532_0
  - intel-openmp=2025.0.0=haa95532_1164
  - ipykernel=6.30.1=py312haa95532_0
  - ipython=9.1.0=py312haa95532_0
  - ipython_pygments_lexers=1.1.1=py312haa95532_0
  - jedi=0.19.2=py312haa95532_0
  - jinja2=3.1.6=py312haa95532_0
  - joblib=1.5.2=py312haa95532_0
  - jpeg=9f=ha349fce_0
  - json5=0.9.25=py312haa95532_0
  - jsonschema=4.25.0=py312haa95532_0
  - jsonschema-specifications=2023.7.1=py312haa95532_0
  - jupyter-lsp=2.2.5=py312haa95532_0
  - jupyter_client=8.6.3=py312haa95532_0
  - jupyter_core=5.8.1=py312haa95532_0
  - jupyter_events=0.12.0=py312haa95532_0
  - jupyter_server=2.16.0=py312haa95532_0
  - jupyter_server_terminals=0.5.3=py312haa95532_0
  - jupyterlab=4.4.7=py312haa95532_0
  - jupyterlab_pygments=0.3.0=py312haa95532_0
  - jupyterlab_server=2.27.3=py312haa95532_0
  - keras=3.11.2=py312h51baaa3_0
  - kiwisolver=1.4.8=py312h5da7b33_0
  - lcms2=2.16=h62be587_1
  - lerc=4.0.0=h5da7b33_0
  - libabseil=20250127.0=cxx17_h52369b4_0
  - libavif=1.1.1=h827c3e9_0
  - libcurl=8.15.0=h2300eb9_0
  - libdeflate=1.22=h5bf469e_0
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.84.2=h405b238_0
  - libgrpc=1.71.0=hf4237ab_0
  - libiconv=1.16=h2bbff1b_3
  - libkrb5=1.21.3=h885b0b7_4
  - libpng=1.6.39=h8cc25b3_0
  - libpq=17.4=h4a159e6_2
  - libprotobuf=5.29.3=h65a231f_1
  - libre2-11=2024.07.02=h5da7b33_0
  - libsodium=1.0.20=h83e8143_0
  - libssh2=1.11.1=h2addb87_0
  - libtiff=4.7.0=h404307b_0
  - libwebp-base=1.3.2=h3d04722_1
  - libxml2=2.13.8=h866ff63_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markdown=3.8=py312haa95532_0
  - markdown-it-py=2.2.0=py312haa95532_1
  - markupsafe=3.0.2=py312h827c3e9_0
  - matplotlib=3.10.6=py312haa95532_0
  - matplotlib-base=3.10.6=py312h43afe63_0
  - matplotlib-inline=0.1.7=py312haa95532_0
  - mdurl=0.1.2=py312haa95532_0
  - mistune=3.1.2=py312haa95532_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.4.0=py312h827c3e9_3
  - mkl_fft=1.3.11=py312h5810407_1
  - mkl_random=1.2.8=py312h8683371_1
  - ml_dtypes=0.5.1=py312h094160a_0
  - mpi=1.0=msmpi
  - mpi4py=4.0.3=py312h827c3e9_0
  - msmpi=10.1.1=had4844c_0
  - msys2-conda-epoch=20160418=1
  - multidict=6.6.3=pyh62beb40_0
  - namex=0.1.0=py312haa95532_0
  - nbclient=0.10.2=py312haa95532_0
  - nbconvert-core=7.16.6=py312haa95532_0
  - nbformat=5.10.4=py312haa95532_0
  - nest-asyncio=1.6.0=py312haa95532_0
  - notebook=7.4.5=py312haa95532_0
  - notebook-shim=0.2.4=py312haa95532_0
  - numexpr=2.11.0=py312ha02bb35_1
  - numpy=2.0.2=py312h12f7302_2
  - numpy-base=2.0.2=py312he4e2855_2
  - openjpeg=2.5.2=h9b5d1b5_1
  - openssl=3.5.4=h725018a_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - optree=0.14.1=py312h214f63a_0
  - overrides=7.4.0=py312haa95532_0
  - packaging=25.0=py312haa95532_0
  - pandas=2.3.2=py312ha5e6156_0
  - pandocfilters=1.5.1=py312haa95532_0
  - papermill=2.6.0=pyhd8ed1ab_2
  - parso=0.8.4=py312haa95532_0
  - pcre2=10.42=h0ff8eda_1
  - pillow=11.3.0=py312hb328d1f_0
  - pip=25.2=pyhc872135_0
  - pixman=0.46.4=h4043f72_0
  - platformdirs=4.3.7=py312haa95532_0
  - prometheus_client=0.21.1=py312haa95532_0
  - prompt-toolkit=3.0.43=py312haa95532_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - propcache=0.3.1=pyhe1237c8_0
  - protobuf=5.29.3=py312h5da7b33_0
  - psutil=7.0.0=py312h02ab6af_0
  - pure_eval=0.2.3=py312haa95532_0
  - pycparser=2.23=py312haa95532_0
  - pygments=2.19.1=py312haa95532_0
  - pyparsing=3.2.0=py312haa95532_0
  - pyqt=6.7.1=py312h378bd72_2
  - pyqt6-sip=13.9.1=py312h02ab6af_2
  - pysocks=1.7.1=py312haa95532_0
  - python=3.12.11=h716150d_0
  - python-dateutil=2.9.0post0=py312haa95532_2
  - python-fastjsonschema=2.20.0=py312haa95532_0
  - python-flatbuffers=24.3.25=py312haa95532_0
  - python-json-logger=3.2.1=py312haa95532_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - pytz=2025.2=py312haa95532_0
  - pywin32=311=py312h885b0b7_0
  - pywinpty=2.0.15=py312h72d21ff_0
  - pyyaml=6.0.2=py312h827c3e9_0
  - pyzmq=27.1.0=py312h7149c55_0
  - qtbase=6.7.3=hd088775_4
  - qtdeclarative=6.7.3=h885b0b7_1
  - qtsvg=6.7.3=h9d4b640_1
  - qttools=6.7.3=hcb596f7_1
  - qtwebchannel=6.7.3=h885b0b7_1
  - qtwebsockets=6.7.3=h885b0b7_1
  - re2=2024.07.02=h214f63a_0
  - referencing=0.30.2=py312haa95532_0
  - requests=2.32.5=py312haa95532_0
  - rfc3339-validator=0.1.4=py312haa95532_0
  - rfc3986-validator=0.1.1=py312haa95532_0
  - rich=13.9.4=py312haa95532_0
  - rpds-py=0.22.3=py312h636fa0f_0
  - scikit-learn=1.7.2=py312h9296b3f_0
  - scipy=1.16.1=py312h86a6471_0
  - send2trash=1.8.2=py312haa95532_1
  - setuptools=72.1.0=py312haa95532_0
  - sip=6.10.0=py312h5da7b33_0
  - six=1.17.0=py312haa95532_0
  - snappy=1.2.1=hcdb6601_0
  - sniffio=1.3.0=py312haa95532_0
  - soupsieve=2.5=py312haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - stack_data=0.6.3=py312haa95532_0
  - tbb=2022.0.0=h214f63a_0
  - tbb-devel=2022.0.0=h214f63a_0
  - tenacity=9.1.2=pyhd8ed1ab_0
  - tensorboard=2.18.0=py312haa95532_0
  - tensorboard-data-server=0.7.0=py312haa95532_1
  - tensorflow=2.18.1=cpu_py312h6605a60_0
  - tensorflow-base=2.18.1=cpu_py312h1ab519a_0
  - termcolor=2.1.0=py312haa95532_0
  - terminado=0.18.1=py312haa95532_0
  - threadpoolctl=3.5.0=py312hfc267ef_0
  - tinycss2=1.4.0=py312haa95532_0
  - tk=8.6.15=hf199647_0
  - tornado=6.5.1=py312h827c3e9_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=py312haa95532_0
  - typing-extensions=4.15.0=py312haa95532_0
  - typing_extensions=4.15.0=py312haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - unicodedata2=15.1.0=py312h827c3e9_1
  - urllib3=2.5.0=py312haa95532_0
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.13=py312haa95532_0
  - webencodings=0.5.1=py312haa95532_2
  - websocket-client=1.8.0=py312haa95532_0
  - werkzeug=3.1.3=py312haa95532_0
  - wheel=0.45.1=py312haa95532_0
  - win_inet_pton=1.1.0=py312haa95532_0
  - winpty=0.4.3=4
  - wrapt=1.17.0=py312h827c3e9_0
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - yarl=1.20.1=pyhe1237c8_0
  - zeromq=4.3.5=h6c54ac7_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - ucimlrepo==0.0.7
prefix: C:\Users\jimen\anaconda3\envs\Distance_copying_TFM
